#!/bin/bash -l
#SBATCH -J SiH2
#SBATCH -q regular
#SBATCH -N 1
#!SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 47:59:59
#SBATCH -o test_silane.o%j

module load molpro
molpro -n 1 dz.com
#molpro -n 8 tz.com
#molpro -n 8 qz.com
#molpro -n 8 5z.com
#molpro -n 8 6z.com
