#!/bin/bash -l
#SBATCH -J silane
#SBATCH -q regular
#SBATCH -N 1
#!SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 20:30:00
#SBATCH -o test_silane.o%j

module load molpro

#molpro -n 8 dz.com
#molpro -n 8 tz.com
#molpro -n 8 qz.com
molpro -n 4 5z.com
#molpro -n 8 6z.com

