#!/bin/bash -l
#SBATCH -J silane
#SBATCH -q regular
#SBATCH -N 1
#!SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 04:00:00
#SBATCH -o test_silane.o%j

module load molpro
#molpro dz.com
molpro -n 2 tz.com
#molpro qz.com
#molpro 5z.com
#molpro 6z.com
